# Generated by Django 4.2.2 on 2023-07-04 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_director_movie_delete_movies_director_movie'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['title']},
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='name',
            new_name='title',
        ),
    ]
